// booklist/mockBooks.js
export const mockBooks = [
  {
    id: 1,
    isbn: '978-3-16-148410-0',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    publisher: "Charles Scribner's Sons",
    publicationYear: 1925,
    isAvailable: true,
  },
  {
    id: 2,
    isbn: '978-1-56619-909-4',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    publisher: 'J.B. Lippincott & Co.',
    publicationYear: 1960,
    isAvailable: false,
  },
  {
    id: 3,
    isbn: '978-0-7432-7356-5',
    title: '1984',
    author: 'George Orwell',
    publisher: 'Secker & Warburg',
    publicationYear: 1949,
    isAvailable: true,
  },
  {
    id: 4,
    isbn: '978-0-14-017739-8',
    title: 'Of Mice and Men',
    author: 'John Steinbeck',
    publisher: 'Penguin Books',
    publicationYear: 1937,
    isAvailable: true,
  },
  {
    id: 5,
    isbn: '978-0-7432-7357-2',
    title: 'Brave New World',
    author: 'Aldous Huxley',
    publisher: 'Chatto & Windus',
    publicationYear: 1932,
    isAvailable: false,
  },
  {
    id: 6,
    isbn: '978-0-06-112008-4',
    title: 'To the Lighthouse',
    author: 'Virginia Woolf',
    publisher: 'Hogarth Press',
    publicationYear: 1927,
    isAvailable: true,
  },
  {
    id: 7,
    isbn: '978-0-7432-7358-9',
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    publisher: 'Little, Brown and Company',
    publicationYear: 1951,
    isAvailable: true,
  },
  {
    id: 8,
    isbn: '978-0-7432-7359-6',
    title: 'Moby-Dick',
    author: 'Herman Melville',
    publisher: 'Harper & Brothers',
    publicationYear: 1851,
    isAvailable: false,
  },
  {
    id: 9,
    isbn: '978-0-7432-7360-2',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    publisher: 'T. Egerton, Whitehall',
    publicationYear: 1813,
    isAvailable: true,
  },
  {
    id: 10,
    isbn: '978-0-7432-7361-9',
    title: 'The Odyssey',
    author: 'Homer',
    publisher: 'Penguin Classics',
    publicationYear: -800,
    isAvailable: true,
  },
];
